### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/ssd2'

### ISSUE THREAD

**Issue by yida1996** [justanhduc/brushstroke-parameterized-style-transfer#1]
Hello justanhduc!
When I run the code 'python nst.py' on linux after installing the Neuralnet-pytorch, there's an error 'PermissionError: [Errno 13] Permission denied: '/ssd2''. How can I deal with the bug?

**Comment by yida1996** [comment]
Does this mean the model hasn't been uploaded yet? 
If so,  could you please share it？Much obliged.

**Comment by justanhduc** [comment]
Hey @yida1996. Please change the paths [here](https://github.com/justanhduc/brushstroke-parameterized-style-transfer/blob/c9d399115709e9859d03fa13a208d04a7d1dcef0/nst.py#L23), [here](https://github.com/justanhduc/brushstroke-parameterized-style-transfer/blob/c9d399115709e9859d03fa13a208d04a7d1dcef0/nst.py#L49) and [here](https://github.com/justanhduc/brushstroke-parameterized-style-transfer/blob/c9d399115709e9859d03fa13a208d04a7d1dcef0/nst.py#L50) to store the results, point to your styles and images.

**Comment by yida1996** [comment]
> Hey @yida1996. Please change the paths [here](https://github.com/justanhduc/brushstroke-parameterized-style-transfer/blob/c9d399115709e9859d03fa13a208d04a7d1dcef0/nst.py#L23), [here](https://github.com/justanhduc/brushstroke-parameterized-style-transfer/blob/c9d399115709e9859d03fa13a208d04a7d1dcef0/nst.py#L49) and [here](https://github.com/justanhduc/brushstroke-parameterized-style-transfer/blob/c9d399115709e9859d03fa13a208d04a7d1dcef0/nst.py#L50) to store the results, point to your styles and images.

It works! Thank you for your patient answer!
